name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'The semver to use'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: gmaclennan/optic-release-automation-action@567cca6b97745b9a698e7df33e0bb30276fd2fbb # v4.12.0 + https://github.com/nearform-actions/optic-release-automation-action/pull/588
        with:
          commit-message: 'chore: Release {version}'
          sync-semver-tags: false
          access: 'public'
          # This prefix is added before the prerelease number, e.g. `v3.0.0-next.0`
          prerelease-prefix: 'next'
          semver: ${{ github.event.inputs.semver }}
          # Prereleases are published under the `next` npm dist-tag
          npm-tag: ${{ startsWith(github.event.inputs.semver, 'pre') && 'next' || 'latest' }}
          # Don't notify linked issues
          notify-linked-issues: false
          publish-mode: 'oidc'
          build-command: |
            npm ci
